
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: datastores.sandeepmultani.github.io
spec:
  group: sandeepmultani.github.io
  names:
    kind: Datastore
    listKind: DatastoreList
    plural: datastores
    singular: datastore
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          status:
            properties:
              datastoreStatus:
                type: string
            type: object
          spec:
            properties:
              image:
                type: string
              database:
                type: string
              port:
                format: int32
                type: integer
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}  

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: datastore-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: datastore-operator
  template:
    metadata:
      labels:
        name: datastore-operator
    spec:
      serviceAccountName: datastore-operator-sa
      containers:
        - name: datastore-operator
          image: sandeepmultani/datastore-operator:0.2.0
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 100m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 128Mi
          # env:
          #   - name: WATCH_NAMESPACE
          #     valueFrom:
          #       fieldRef:
          #         fieldPath: metadata.namespace
          #   - name: LOG_LEVEL
          #     value: "debug"
          #   - name: RETRY_MAX_ATTEMPTS
          #     value: "3"
          #   - name: RETRY_INITIAL_DELAY
          #     value: "5000"
          #   - name: RETRY_DELAY_MULTIPLIER
          #     value: "1.5"
      terminationGracePeriodSeconds: 10          

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: datastore-operator-sa 

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: datastore-operator-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - services/finalizers
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
- apiGroups:
  - apps
  resourceNames:
  - datastore-operator
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - replicasets
  - deployments
  verbs:
  - get
- apiGroups:
  - sandeepmultani.github.io
  resources:
  - '*'
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: datastore-operator-role-binding
subjects:
- kind: ServiceAccount
  name: datastore-operator-sa
roleRef:
  kind: Role
  name: datastore-operator-role
  apiGroup: rbac.authorization.k8s.io