
apiVersion: v1
kind: Namespace
metadata:
  name: operator-ns

---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: datastores.sandeepmultani.github.io
spec:
  group: sandeepmultani.github.io
  names:
    kind: Datastore
    listKind: DatastoreList
    plural: datastores
    singular: datastore
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          status:
            properties:
              datastoreStatus:
                type: string
            type: object
          spec:
            properties:
              image:
                type: string
              database:
                type: string
              port:
                format: int32
                type: integer
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}  

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    operator-deployment: datastoreoperator
  name: datastoreoperator
  namespace: operator-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      operator: datastoreoperator
  template:
    metadata:
      labels:
        operator: datastoreoperator
    spec:
      containers:
      - name: datastoreoperator
        image: sandeepmultani/datastore-operator:0.0.2
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 64Mi
      terminationGracePeriodSeconds: 10

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: operator-sa      

---      
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: datasourceoperator-cluster-role
rules:
- apiGroups: ["sandeepmultani.github.io"]
  resources: ["datastore"]
  verbs: ["get", "watch", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: datasourceoperator-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: datasourceoperator-cluster-role
subjects:
- kind: ServiceAccount
  name: operator-sa
  namespace: operator-ns  