
apiVersion: v1
kind: Namespace
metadata:
  name: system

---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: datastores.sandeepmultani.github.io
spec:
  group: sandeepmultani.github.io
  names:
    kind: Datastore
    listKind: DatastoreList
    plural: datastores
    singular: datastore
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          status:
            properties:
              datastoreStatus:
                type: string
            type: object
          spec:
            properties:
              image:
                type: string
              database:
                type: string
              port:
                format: int32
                type: integer
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}  

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    operator-deployment: datastoreoperator
  name: operator
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      operator: datastoreoperator
  template:
    metadata:
      labels:
        operator: datastoreoperator
    spec:
      containers:
      - env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
#        envFrom:
#        - configMapRef:
#            name: webhook-config
        image: sandeepmultani/datastore-operator:0.0.1
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          timeoutSeconds: 1
        name: operator
        ports:
        - containerPort: 5000
          name: http
        readinessProbe:
          httpGet:
            path: /ready
            port: http
          initialDelaySeconds: 15
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 64Mi
      terminationGracePeriodSeconds: 10

---      
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: operator-role
rules:
- apiGroups:
  - sandeepmultani.github.io
  resources:
  - datastores
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - get
  - list
  - update
- apiGroups:
  - ""
  - admissionregistration.k8s.io
  resources:
  - services
  - validatingwebhookconfigurations
  - mutatingwebhookconfigurations
  verbs:
  - create
  - get
  - patch
  - update
  - delete
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
- apiGroups:
  - sandeepmultani.github.io
  resources:
  - datastores/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - services/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apps
  resources:
  - deployments/status
  verbs:
  - get
  - patch
  - update

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: operator-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: operator-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: system  