apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: cars.sandeepmultani.github.io
spec:
  group: sandeepmultani.github.io
  names:
    kind: Car
    listKind: CarList
    plural: cars
    singular: car
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          status:
            properties:
              carStatus:
                type: string
            type: object
          spec:
            properties:
              color:
                type: string
              gearbox:
                type: string
              model:
                format: int32
                type: integer
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}